### ISSUE TITLE
Yamllint fail (.ip_authenticated.yaml)

### ISSUE THREAD

**Issue by allanpersson** [custom-components/authenticated#38]
**Version of the custom_component**

0.5.0

**Describe the bug**
The file _.ip_authenticated.yaml_ is failing yamllint because of missing **---** in start of file. If you edit the file manually with the missing --- it gets overwritten by the component.
![Home Assistant 3-7-2019 12-57-38](https://user-images.githubusercontent.com/46043392/60586701-e1c3c380-9d92-11e9-84c0-bb6306a24988.png)

**log**

```
Add your logs here.
```

**Comment by ludeeus** [comment]
Not really an issue...
But added in 1.0.0 <https://github.com/custom-components/authenticated/releases/tag/1.0.0>

**Comment by allanpersson** [comment]
Thanks for pleasing my OCD 😘🙏
