### ISSUE TITLE
Authenticated not showing any location information anymore

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/authenticated#43]
**Version of the custom_component**

**Describe the bug**
Prior to v1, the sensor used to show the location information country/region/city but now is blank. Otherwise now working well
**log**

![Untitled](https://user-images.githubusercontent.com/36390762/60850083-00153d80-a231-11e9-88ef-056a4b92638f.png)

**Comment by ludeeus** [comment]
This is 3 issues.. :/

1: the API providers have rate limits.
2: extreme-ip does not support IPv6
3: data from vigilante is not correctly parsed.

ipapi provider (default) should be able to show this as long as you do not hit the ratelimit.

**Comment by DavidFW1960** [comment]
Hmm.... I have not configured anything in there for provider so should be default.. It has always worked with IPv6 actually... that screenshot is google assistant and it's always worked fine. I'll check my config for provider.
```
# Sensors
sensor:

# Authentication Sensor
  - platform: authenticated
    enable_notification: true
```

**Comment by DavidFW1960** [comment]
I had deleted .ip_authenticated.yaml and checking that file now I only have 5 entries and none of them show a location. Checked the logs and there are no entries for authenticated at all - I used to get quite a lot.

**Comment by ludeeus** [comment]
default is ipapi, that support v6, but you have probably hit the ratelimit

**Comment by DavidFW1960** [comment]
I've never hit it before. I have 12 entries in the yaml file (3 days) This is nowhere near as many entries as I was expecting

**Comment by ludeeus** [comment]
The entries are from .storage/auth, they may be old.

**Comment by DavidFW1960** [comment]
Um... ok... just logged out and in again. In .ip_auth yaml it shows me logging back in at   last_used_at: '2019-07-08T22:58:08.984340+00:00'. It should be 2019-07-09T07:25:00+00:00 I don't have a single entry in there for today. I also added ipapi as a provider (in single quotes).... nothing.

**Comment by ludeeus** [comment]
that is not how it works.

the entry for existing IP's will only be updated when needed (refresh token expired)
and adding ipapi does not matter, that is _default_

I started this thread by stating rate limit was an issue did I not?

> 1: the API providers have rate limits.

No matter how you configure that it will still be an issue with how it operates, this **need** to change in the code.

**Comment by DavidFW1960** [comment]
You did state that but it does not make sense... I was just eliminating the possibility it wasn't using it as the default. Like I said I have not see this rate limit previously and zero geo data for 3 days of entries in the yaml file isn't normal.

If you are sure that's all it is then I'll see what happens tomorrow.

**Comment by ludeeus** [comment]
before it did not query during startup, it does now, and that is too much for the API.

**Comment by DavidFW1960** [comment]
Ok thanks for the explanation. I’ll see what happens tomorrow. Doesn’t really matter anyway I suppose it was just different to before.

**Comment by ludeeus** [comment]
1.0.6 fixes all issues mentioned in this issue.
if you want a reindex of geodata, delete `.ip_authenticated.yaml` then restart HA.

**Comment by DavidFW1960** [comment]
Thanks @ludeeus that seems to be working again now.
