### ISSUE TITLE
Work through reverse proxy

### ISSUE THREAD

**Issue by jimmyeao** [custom-components/authenticated#49]
**Describe the solution you'd like**

Correct reporting of IP addresses when using a reverse proxy. Currently, only the reverse proxy IP is listed.

**Comment by ludeeus** [comment]
If that is the case you have wrongly configured Home Assistant.
This integration used the IP that HA see.

**Comment by jimmyeao** [comment]
HASS is fine. It is exposed to the internet through a reverse proxy (NGINX) as are other internal hosts.

**Comment by DavidFW1960** [comment]
@jimmyeao see the note for configuring http in home assistant - if you don't set a trusted proxy and set x_forwarded_for to true then every IP address reported to HA will be the address of the proxy....

**Comment by jimmyeao** [comment]
I’ll double check, thanks :)

Jimmy White
________________________________
