### ISSUE TITLE
Recent update made a new folder /custom_components/None/authenticated

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/authenticated#50]
**Version of the custom_component**

Newest via HACS
**Describe the bug**
Updated via HACS and it made a new sub-folder None and made authenticated under there
**log**

```
Add your logs here.
```
No log - it's working. I just moved it back where it's supposed to be.....

**Comment by DavidFW1960** [comment]
.storage seems to be looking in the right place.... maybe this is a HACS issue?

**Comment by ludeeus** [comment]
It's fixed in the beta branch.
