### ISSUE TITLE
UTC time in notification?

### ISSUE THREAD

**Issue by andriej** [custom-components/authenticated#51]
I like the addon, but the login time seems to show UTC instead of physical time at location.

I use HA in venv, so the system timezone should be ok. Also HA doesn't have issue with proper time.

**Comment by ludeeus** [comment]
That timestamp are indeed in UTC and are fetched directly from the file that HA creates.
I will not add local TZ support to this, but if anyone else adds a PR for it I will happily accept it :)

**Comment by andriej** [comment]
@ludeeus - I don't know python, tho I know HA is putting out timezone for components to use...
