### ISSUE TITLE
exclude range of IPs

### ISSUE THREAD

**Issue by enrysan0** [custom-components/authenticated#53]
Hi,

Is it possible to exclude range of IPs?
My intent is to exclude the range of Google Assistant Server's IPs that are logged everytime I use a vocal command with Gooogle Home.
Thanks

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/73140231-e88b8e00-4076-11ea-82d5-9aaf380ccd0e.png)

**Comment by enrysan0** [comment]
Thanks for this NO answer. Next time please spent more time trying to understand the question before amswer with an immage and close an issue.

I asked how to exclude a RANGE of IP not a LIST of IP.
The difference is between write something like "192.168.1.0/24" and have to write a full liste of 250 IPs:
- 192.168.150.1
- 192.168.150.2
- 192.168.150.3
-......... x 200 times
- 192.168.150.253
- 192.168.150.254

Now do you understand my question if is possible to exclude range of IPs?

THANKS
