### ISSUE TITLE
Thanks and query

### ISSUE THREAD

**Issue by atcapollo** [custom-components/authenticated#56]
Not issue per se first just to say this is excellent. It should be part of core HASS it's that important.

Second how is the code hooking into the user login in events? Is it tailing a log file?

The code seems to pick up self.hass.config.path(".storage/auth") but I am not sure what this actually is. Welcome some pointers as I like to do something similar and play an alert chime / Hass automation everytime a new log in event occurs. Rather that the state returning the IP I want the state to return the username and location.

Thanks

**Comment by ludeeus** [comment]
Thanks 👍 

`.storage/auth` is a file in your configdir, which keeps a ledger of logins, which I use in this integration.
This works for this integration, but it will probably not for any other integration, there are other methods of getting that data.

The #integrations channel on the HA discord server might be able to help you with that.
Closing this as it's not an issue with this integration.
