### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by beikeland** [custom-components/authenticated#62]
**Is your feature request related to a problem? Please describe.**
Given the ratelimit from github when using HACS I would encourage adding some instructions to installing from git without using HACS.

**Describe the solution you'd like**
I did (as the user with write permissions to the config folder for my docker container):
```
cd ~/homeassistant
mkdir -p ./custom_components
git clone https://github.com/custom-components/authenticated.git
ln -s authenticated/custom_components/authenticated ./custom_components 
```
restart home assistant and then add 
```
sensor:
  - platform: authenticated
```
to configuration.yaml

**Describe alternatives you've considered**
I appreicate there other types of installations than docker to cater to, but I recon the HA core users will adapt nicely and I have no experience with hass.io

**Additional context**
If nothing else people might find this as closed issue.

**Comment by GirzzlyAK** [comment]
I don't use HACS, and wonder how I would install this on a Home Assistant OS installation.

**Comment by DavidFW1960** [comment]
> I don't use HACS, and wonder how I would install this on a Home Assistant OS installation.
Download all files in the custom_component_authenticated folder in RAW mode and configure as per the instructions after restarting HA. Don't try configuring until you restart HA.

**Comment by beikeland** [comment]
Not familiar with HA OS, but if you know where the config.yaml file is then just ssh in and change to that directory and/or user and follow my post. Possibly after doing `sudo apt install git` if git is missing in the HA OS image)

If you have trouble finding where to put it I guess `sudo find / -name config.yaml 2>/dev/null` might offer a few suggestions to look closer at. Using `ls -l ` on the config.yaml file to see what user it is might also be helpfull.

**Comment by GirzzlyAK** [comment]
Cool. Thanks.
