### ISSUE TITLE
Version Key

### ISSUE THREAD

**Issue by Ante987** [custom-components/authenticated#65]
Hi
On every boot i get this in my log:
`No 'version' key in the manifest file for custom integration 'authenticated'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'authenticated'`
In on Intel Nuc with debian Docker and Home-Assistant core

Is there any plans for this to be fixed?
Best regards
Andreas

**Comment by ludeeus** [comment]
Eventually

**Comment by Ante987** [comment]
Ok thanks, didnt find any info about it but now i know. :-)

**Comment by ludeeus** [comment]
<https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes> outlines the information as for why
