### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by r3ndszergazda** [custom-components/authenticated#69]
Login info is displayed in UTC time even though the main timezone setting in configuration.yaml is set to the correct one.
It would be great if it was possible to use the "correct" time.

Versions are: core-2021-3.3, supervisor-2021.03.4, HassOS 5.12, HACS 1.11.3, Authenticated 21.3.0

**Comment by ludeeus** [comment]
This does not and should not modify the dataset, that is handled by Home Assistant itself, and therefore should be UTC like anything else backend related in Home Assistant.
