### ISSUE TITLE
Platform only detects local IP addresses

### ISSUE THREAD

**Issue by elbueno222** [custom-components/authenticated#70]
**Version of the custom_component**
21.3.0 (installed using HACS)

**Describe the bug**
This platform works fine reporting the IP address when I connect to HA from my local network (IP 192.x.x.x or 172.x.x.x) but it doesn´t update the IP address when I connect to HA from an external IP (i.e. using the phone with mobile data instead of wifi)

**log**

```
Not sure how to get the logs from this Platform, but happy to include them if someone tells me how to get them
```

**Comment by ludeeus** [comment]
Then you are using a proxy and have have misconfigured your http integration, this just reads the data that HA gets.
https://www.home-assistant.io/integrations/http/

**Comment by elbueno222** [comment]
> Then you are using a proxy and have have misconfigured your http integration, this just reads the data that HA gets.
> https://www.home-assistant.io/integrations/http/

I am not using a proxy and haven´t configured the http integration (according to the instructions in the link you provide "You only need to add this to your configuration file if you want to change any of the default settings.")

**Comment by DavidFW1960** [comment]
> I am not using a proxy and haven´t configured the http integration (according to the instructions in the link you provide "You only need to add this to your configuration file if you want to change any of the default settings.")

You need x_forwarded_for: true and to configure a trusted_proxy in the http section. NGINX also needs to be configured to pass through the x_forwarded_for header which will reveal the true IP address.

**Comment by elbueno222** [comment]
> > I am not using a proxy and haven´t configured the http integration (according to the instructions in the link you provide "You only need to add this to your configuration file if you want to change any of the default settings.")
> 
> You need x_forwarded_for: true and to configure a trusted_proxy in the http section. NGINX also needs to be configured to pass through the x_forwarded_for header which will reveal the true IP address.

Thanks both, after applying the changes it works!!
