### ISSUE TITLE
New login from user "Hass.io"

### ISSUE THREAD

**Issue by vikdb** [custom-components/authenticated#71]
Ever so often i get a notification and a warning in the logs about a new login from user "Hass.io".
Is this normal? or should i be worried that my system is compromised?

or is it just nabu casa changing IP every X days? 

```
This error originated from a custom integration.

Logger: custom_components.authenticated.sensor
Source: custom_components/authenticated/sensor.py:200
Integration: authenticated (documentation, issues)
First occurred: 5:38:31 PM (1 occurrences)
Last logged: 5:38:31 PM

New successful login from unknown IP (x.x.x.x)
```

**Comment by ludeeus** [comment]
You asked on the HA discord, that is the place to ask, it's a valid user so other than the notification (which is expected), these questions are not something for this tracker.
