### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by RogerSelwyn** [custom-components/authenticated#76]
I get the following error in my log. It just needs 'device' changing to 'extra' in the relevant method.

`2021-12-11 22:21:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.last_successful_authentication (<class 'custom_components.authenticated.sensor.AuthenticatedSensor'>) implements device_state_attributes. Please report it to the custom component author.`

**Comment by timutta** [comment]
This can be fixed with by (meanwhile in case anyone wants to fix this, they can change the value manually from HA).

In [config folder]\custom_components\authenticatedt\sensor.py, line 241, replace device_state_attributes with extra_state_attributes

**Comment by ludeeus** [comment]
https://github.com/custom-components/authenticated/pull/77
