### ISSUE TITLE
Show username etc in sensor

### ISSUE THREAD

**Issue by mikael-andersson** [custom-components/authenticated#83]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
I would like a sensor to show me the username or more or less all information I see in the file .ip_autenticated.yaml. If one has several users on a system you would see exactly who have logged in.

**Describe alternatives you've considered**
An alternative is to read the file .ip_autenticated.yaml but it is 'nicer' to get the information such as username straight in to Home Assistant.

**Additional context**
NA

**Comment by maymaymay** [comment]
Isn't that what You want?
![obraz](https://user-images.githubusercontent.com/6071653/164417424-d8c90063-56b3-4222-b7ba-7ea361a6a944.png)

**Comment by mikael-andersson** [comment]
Yes. :) How do I see that?

**Comment by maymaymay** [comment]
Chang 241 line in sensor.py to:
`    def extra_state_attributes(self):`

**Comment by mikael-andersson** [comment]
Works great, many thanks! :) I might create a pull request in order to add this information to README.md.

**Comment by maymaymay** [comment]
That change is already done, but not released to HACS yet.

**Comment by mikael-andersson** [comment]
OK, sounds good, thanks again for your engagement.
