### ISSUE TITLE
Cloudflare IP shown

### ISSUE THREAD

**Issue by codeinstitution** [custom-components/authenticated#84]
**21.9.0**

When I login, the notification is showing cloudflare ips, not the x_forwarded_for ip address. I have nginx acting as a reverse proxy and cloudflare sending requests to the nginx.

**Comment by ludeeus** [comment]
If that is true, then your Home Assistant configuration is wrong, this integration does not care at all about that, it takes whatever HA thinks was used.
https://www.home-assistant.io/integrations/http/
