### ISSUE TITLE
I would like to have a lovelace card to show the last X number of logins

### ISSUE THREAD

**Issue by allenrobberson** [custom-components/authenticated#85]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
I would like to have a lovelace card to show the last X number of logins

**Describe alternatives you've considered**
none

**Additional context**
I would like to have a card that would show the last x number of logins so when i load my lovelace it will show me without having to open the logs

**Comment by ludeeus** [comment]
Use Logbook card

**Comment by allenrobberson** [comment]
Can i ask what the entity name would be?
